- name: Create env dir
  file:
    path: /etc/metoffice_weather
    state: directory
    mode: "0700"

- name: Inject prod env vars
  copy:
    dest: /etc/metoffice_weather/.env
    mode: "0600"
    content: |
      DJANGO_SECRET_KEY={{ DJANGO_SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS={{ ALLOWED_HOSTS }}
      DB_NAME={{ POSTGRES_DB }}
      DB_USER={{ POSTGRES_USER }}
      DB_PASSWORD={{ POSTGRES_PASSWORD }}
      DB_HOST={{ POSTGRES_HOST }}

