events {}

http {
  upstream metoffice_weather_upstream {
    server metoffice_weather:8000;
  }

  server {
    listen 80;

    
    location / {
      proxy_pass http://metoffice_weather_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_redirect off;
    }

    location /static/ {
      alias /usr/src/metoffice_weather/staticfiles/;
      expires 30d;
      access_log off;
      add_header Cache-Control "public";
    }

    location /media/ {
      alias /usr/src/metoffice_weather/media/;
      expires 30d;
      access_log off;
    }

    location = /favicon.ico {
      alias /usr/src/metoffice_weather/staticfiles/core/assets/svg/brands/gitlab-gray.svg; 
      log_not_found off;
      access_log off;
    }

  }
}