- name: Create app directory
  file:
    path: /srv/metoffice_weather
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Pull image
  command: docker pull shailendershrma/metoffice_weather:{{ image_tag }}

- name: Update compose file
  template:
    src: docker-compose.prod.yml.j2
    dest: /srv/metoffice_weather/docker-compose.prod.yml

- name: Copy nginx config
  copy:
    src: nginx.conf
    dest: /srv/metoffice_weather/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: Start core services (db + redis)
  command: docker compose -f docker-compose.prod.yml up -d redis db
  args:
    chdir: /srv/metoffice_weather

- name: Wait for DB
  shell: |
    until docker exec metoffice_weather-db pg_isready; do sleep 2; done

- name: Run database migrations
  command: docker compose -f docker-compose.prod.yml run --rm --no-deps metoffice_weather python manage.py migrate
  args:
    chdir: /srv/metoffice_weather

- name: Start all services
  command: docker compose -f docker-compose.prod.yml up -d
  args:
    chdir: /srv/metoffice_weather

- name: Reset SSH connection to apply docker group
  meta: reset_connection