- name: Remove old Docker packages if any
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  ignore_errors: true
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
      gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) \
    signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker Engine + Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: true
  
- name: Login to DockerHub
  command: docker login -u {{ docker_user }} -p {{ docker_pat }}
  no_log: true

- name: Pull private Docker image
  command: docker pull shailendershrma/metoffice_weather:{{ image_tag }}